# Generated by Django 5.1.6 on 2025-02-16 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_dailypuzzle_date_alter_dailypuzzle_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypuzzle',
            name='elo_rating',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name='dailypuzzle',
            name='last_compared',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dailypuzzle',
            name='match_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailypuzzle',
            name='canvas',
            field=models.FileField(upload_to='puzzles/'),
        ),
        migrations.AlterField(
            model_name='dailypuzzle',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailypuzzle',
            name='prompt',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('selected_puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_won', to='canvas.dailypuzzle')),
                ('shown_puzzles', models.ManyToManyField(related_name='comparisons_shown', to='canvas.dailypuzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
