# Generated by Django 5.1.6 on 2025-02-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_dailypuzzle_elo_rating_dailypuzzle_last_compared_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypuzzle',
            name='canvas',
            field=models.FileField(blank=True, upload_to='puzzles/'),
        ),
    ]
