# Generated by Django 5.1.6 on 2025-02-16 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_alter_dailypuzzle_canvas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypuzzle',
            name='canvas',
            field=models.FileField(blank=True, null=True, upload_to='puzzles/'),
        ),
        migrations.AlterField(
            model_name='dailypuzzle',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailypuzzle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
